"""event entity added

Revision ID: 1272d8bf8638
Revises: 
Create Date: 2025-09-07 10:07:42.699950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1272d8bf8638'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
    INSERT INTO event (title, description) VALUES
    ('Városi Jazz Est', 'Szabadtéri koncert helyi és vendégzenekarokkal a főtéren.'),
    ('Tech Meetup 12', 'Villámelőadások Flaskról, SQLAlchemy-ről és tesztelésről.'),
    ('Karácsonyi Vásár', 'Kézműves standok, forralt bor, családi programok.'),
    ('Közösségi Filmklub', 'Vetítés és kötetlen beszélgetés a filmről a végén.'),
    ('Irodalmi Est', 'Kortárs szerző felolvasása és dedikálás.'),
    ('Startup Pitch Night', 'Kezdő vállalkozások háromperces bemutatókkal.'),
    ('FotósétA A Belvárosban', 'Városi fotózás kezdőknek és haladóknak.'),
    ('Jóga A Parkban', 'Reggeli ászanák és légzőgyakorlatok minden szinten.'),
    ('Gasztro Workshop', 'Konyhai alaptechnikák és szezonális receptek.'),
    ('Borfeszt Hétvége', 'Hazai pincészetek kóstolója és szakmai beszélgetések.'),
    ('Adventi Kóruskoncert', 'Karácsonyi dalok vegyeskarral a dóm előtti téren.'),
    ('Táncház – Moldvai', 'Élő zene és tánctanítás kezdőknek.'),
    ('Közösségi Futónap', '5 és 10 km-es távok időméréssel, jótékonysági célokkal.'),
    ('Asztali Játék Est', 'Társasjátékok kipróbálása barátságos hangulatban.'),
    ('Csillagászati Éjszaka', 'Távcsöves megfigyelés és ismeretterjesztő előadás.'),
    ('Állásbörze', 'Cégek bemutatkozása és villáminterjúk pályakezdőknek.'),
    ('Nyelvcsere Klub', 'Kötetlen beszélgetés több nyelven kávé mellett.'),
    ('Adatvizualizáció Workshop', 'Bevezetés a grafikonok és dashboardok világába.'),
    ('Klasszikus Est', 'Vonósnégyes koncert Beethoven és Dvořák műveiből.'),
    ('Kertészeti Tréning', 'Városi kertészkedés alapjai és komposztálás.'),
    ('Önkéntes Nap', 'Városszépítő akció közösségi festéssel és takarítással.'),
    ('Vegan Brunch Pop-up', 'Szezonális növényi ételek kóstolója élő zenével.'),
    ('Robotika Bemutató', 'Diákprojektek és interaktív robotok kipróbálása.'),
    ('Poetry Slam', 'Slam költészet nyílt mikrofonnal és közönségszavazással.');
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
