"""create auth and relation tables and seed admin

Revision ID: 2a9b8c4f1d7f
Revises: 1272d8bf8638
Create Date: 2025-12-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9b8c4f1d7f'
down_revision = '1272d8bf8638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
        sa.UniqueConstraint('email', name='uq_user_email')
    )

    op.create_table(
        'category',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.UniqueConstraint('name', name='uq_category_name')
    )

    op.create_table(
        'event_categories',
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('event_id', 'category_id'),
        sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], )
    )

    op.create_table(
        'reservation',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.UniqueConstraint('event_id', 'user_id', name='uq_event_user')
    )

    # seed admin user with precomputed password hash (password: admin)
    op.execute("""
    INSERT INTO `user` (name, email, password_hash, role, created_at) VALUES
    ('Admin', 'admin@example.com', 'scrypt:32768:8:1$tsWXiJNq8YXg63xo$8b6b1c190629e0d3a1b5fe4cc5034a24bff43e884b596130005bddf0ac3aee933477849af10f57c145d7c5444c112cc772c219f598153ebd7699c91c23f846ef', 'admin', UTC_TIMESTAMP());
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('event_categories')
    op.drop_table('category')
    op.drop_table('user')
    # ### end Alembic commands ###
